// <auto-generated />
using System;
using FinanzautoAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanzautoAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722161403_AddVehicleImageMiddleTable")]
    partial class AddVehicleImageMiddleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanzautoAPI.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blanco"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Negro"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gris"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Plateado"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rojo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Azul"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Verde"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Amarillo"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Marrón"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Beige"
                        });
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.ModelLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("ModelLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "Hilux"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "Yaris"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "Onix"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            Name = "Tracker"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Name = "Spark GT"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 3,
                            Name = "Duster"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            Name = "Stepway"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Name = "Logan"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 4,
                            Name = "Mazda 2"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 4,
                            Name = "Mazda 3"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 4,
                            Name = "CX-5"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 5,
                            Name = "Versa"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 5,
                            Name = "Frontier"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 5,
                            Name = "Sentra"
                        });
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("ModelLineId")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VehicleStatusId")
                        .HasColumnType("int");

                    b.Property<short>("YearReleased")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ModelLineId");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.HasIndex("VehicleStatusId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.VehicleImage", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("VehicleImages");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.VehicleObservation", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("ObservationId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId", "ObservationId");

                    b.HasIndex("ObservationId");

                    b.ToTable("VehicleObservations");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.VehicleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("VehicleStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Disponible"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reparación"
                        },
                        new
                        {
                            Id = 3,
                            Name = "En vitrina"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vendido"
                        });
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.ModelLine", b =>
                {
                    b.HasOne("FinanzautoAPI.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.Vehicle", b =>
                {
                    b.HasOne("FinanzautoAPI.Entities.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanzautoAPI.Entities.ModelLine", "ModelLine")
                        .WithMany()
                        .HasForeignKey("ModelLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanzautoAPI.Entities.VehicleStatus", "VehicleStatus")
                        .WithMany()
                        .HasForeignKey("VehicleStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("ModelLine");

                    b.Navigation("VehicleStatus");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.VehicleImage", b =>
                {
                    b.HasOne("FinanzautoAPI.Entities.Image", "Image")
                        .WithMany("VehicleImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanzautoAPI.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.VehicleObservation", b =>
                {
                    b.HasOne("FinanzautoAPI.Entities.Observation", "Observation")
                        .WithMany("VehicleObservations")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanzautoAPI.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleObservations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.Image", b =>
                {
                    b.Navigation("VehicleImages");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.Observation", b =>
                {
                    b.Navigation("VehicleObservations");
                });

            modelBuilder.Entity("FinanzautoAPI.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleImages");

                    b.Navigation("VehicleObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
